kind: Deployment
apiVersion: apps/v1
metadata:
  name: keycloak
spec:
  template:
    spec:
      containers:
        - name: keycloak
          env:
            - name: KC_HOSTNAME
              value: userservice-keycloak-projectgroup1-test.apps.inholland-minor.openshift.eu
